name: Run Tests for find_lowest_number.py

on: [push]

jobs:
  test-script:
    name: Test find_lowest_number.py
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Set up Python
        uses: actions/setup-python

      - name: Test 1 - File with 10 numbers
        run: |
          python3 find_lowest_number.py test_data/test1_input.txt output1.txt
          diff output1.txt test_data/test1_expected.txt

      - name: Test 2 - File with 1 number
        run: |
          python3 find_lowest_number.py test_data/test2_input.txt output2.txt
          diff output2.txt test_data/test2_expected.txt

      - name: Test 3 - Blank file
        run: |
          python3 find_lowest_number.py test_data/test3_input.txt output3.txt
          diff output3.txt test_data/test3_expected.txt
